spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=ecommerce
spring.jpa.show-sql=true
server.port=8084
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
